theme: jekyll-theme-cayman
exclude: [.gitignore, notes.sln, Gemfile, Gemfile.lock]
title: ~ Programming notes ~
description: A small site with personal notes.
collections:
  language-reference:
    output: true
plugins:
  - jekyll-sitemap